import { useMemo, useState } from "react";
import { calculateBudget, demoRoles, fitForPerson, type DemoBudget, type DemoBudgetRosterLine, type DemoSystem } from "./demo-system";
import type { ScreenSpec } from "./screen-data";
import type { StaffingRequest } from "./staffing-workflow";

const levelNames = ["Beginner", "Intermediate", "Advanced", "SME"];
const roles = demoRoles;
const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

function DemoTag({ children, tone = "neutral" }: { children: string; tone?: "good" | "warn" | "bad" | "neutral" }) {
  return <span className={`status-pill ${tone}`}><i />{children}</span>;
}

function DemoBanner({ label, title, description, children }: { label: string; title: string; description: string; children?: React.ReactNode }) {
  return <section className="demo-section-banner"><div><span>{label}</span><h2>{title}</h2><p>{description}</p></div>{children}</section>;
}

function EmptyState({ title, detail, action, onAction }: { title: string; detail: string; action?: string; onAction?: () => void }) {
  return <div className="operational-empty"><span>◇</span><strong>{title}</strong><p>{detail}</p>{action && <button className="primary-button" onClick={onAction}>{action}</button>}</div>;
}

export function DemoHome({ system, onSelect }: { system: DemoSystem; onSelect: (id: string) => void }) {
  const approved = system.state.budgets.filter((item) => item.state === "Approved").length;
  const pendingClaims = system.state.claims.filter((item) => item.state === "Pending").length;
  const submittedTime = system.state.timesheets.filter((item) => item.state === "Submitted").length;
  return <>
    <DemoBanner label="Production-quality static demo" title={`Welcome, Maya · ${system.state.activeRole}`} description="Complete the governed path using sanitized browser data. Every decision updates notifications and the immutable demo audit stream."><button className="secondary-button inverse" onClick={() => onSelect("GLB-05")}>Switch role</button></DemoBanner>
    <section className="stat-grid"><article className="stat-card"><div><span>Approved budgets</span></div><strong>{approved}</strong><p><b>✓</b> Staffing-gate ready</p></article><article className="stat-card"><div><span>Accepted allocations</span></div><strong>{system.state.allocations.length}</strong><p><b>↗</b> Effective-dated demo lines</p></article><article className="stat-card"><div><span>Pending skill reviews</span></div><strong>{pendingClaims}</strong><p><b>!</b> Manager action</p></article><article className="stat-card"><div><span>Submitted timesheets</span></div><strong>{submittedTime}</strong><p><b>•</b> Awaiting decision</p></article></section>
    <section className="surface golden-path"><div className="surface-heading"><div><span className="section-kicker">R1 golden path</span><h2>Run the complete demo workflow</h2></div><DemoTag tone="good">Operational</DemoTag></div><div className="path-steps">{[
      ["1", "Approve a project budget", "Validate calculated economics and approval routing.", "BUDUI-09"],
      ["2", "Review capability supply", "Inspect skills, credentials and candidate fit.", "SKLUI-17"],
      ["3", "Create a staffing request", "Submit a budget-covered candidate request.", "STFUI-13"],
      ["4", "Make the Staffer decision", "Commit capacity through a human checkpoint.", "STFUI-21"],
      ["5", "Submit and approve time", "Use the accepted allocation for eligible actuals.", "TIMEUI-01"],
    ].map(([number, title, detail, id]) => <button key={id} onClick={() => onSelect(id)}><i>{number}</i><span><strong>{title}</strong><small>{detail}</small></span><b>→</b></button>)}</div></section>
  </>;
}

export function NotificationDemo({ system, onSelect }: { system: DemoSystem; onSelect: (id: string) => void }) {
  return <section className="surface operational-list"><div className="surface-heading"><div><span className="section-kicker">Accountable alert lifecycle</span><h2>Notifications and exceptions</h2></div><button className="secondary-button" onClick={system.markNotificationsRead}>Mark all read</button></div>{system.state.notifications.length ? system.state.notifications.map((item) => <article className={`notification-row ${item.read ? "read" : ""}`} key={item.id}><span className={`notification-severity ${item.severity.toLowerCase()}`}>!</span><span><strong>{item.title}</strong><small>{item.detail}</small><small>Owner: {item.owner ?? "Unassigned"} · First seen {item.firstSeen}{item.closureNote ? ` · Closure: ${item.closureNote}` : ""}</small></span><time>{item.time}</time><DemoTag tone={item.resolution === "Closed" ? "good" : "warn"}>{item.resolution}</DemoTag><div className="button-cluster"><button className="row-action" onClick={() => onSelect(item.title.includes("Budget") ? "BUDUI-09" : item.title.includes("Capability") ? "SKLUI-14" : "STFUI-21")}>Open</button>{item.resolution === "Open" && <button className="row-action" onClick={() => system.closeNotification(item.id, "Owner validated the mock trigger and corrective evidence.")}>Close</button>}</div></article>) : <EmptyState title="Inbox is clear" detail="Decision, compliance and data-quality events will appear here." />}</section>;
}

export function RoleDemo({ system, onSelect, onToast }: { system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  return <section className="surface role-workspace"><div className="form-heading"><span className="section-kicker">Demo identity and scope</span><h2>Choose an active business role</h2><p>The static demo changes navigation context and attributes every subsequent audit event to this role.</p></div><div className="role-grid">{roles.map((role) => <button className={system.state.activeRole === role ? "active" : ""} key={role} onClick={() => system.setRole(role)}><i>{role.slice(0, 2).toUpperCase()}</i><span><strong>{role}</strong><small>Salesforce COE · India</small></span>{system.state.activeRole === role && <b>Active</b>}</button>)}</div><div className="sticky-actions"><span /><button className="primary-button" onClick={() => { onToast(`Active role changed to ${system.state.activeRole}`); onSelect("GLB-02"); }}>Apply role and scope →</button></div></section>;
}

export function EngagementDemo({ screen, system, onSelect }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void }) {
  const rows = system.state.budgets.map((budget) => {
    const calc = calculateBudget(budget);
    const allocations = system.state.allocations.filter((item) => item.engagement === budget.engagement).length;
    return { budget, calc, allocations };
  });
  if (screen.id === "ENG-01") return <><DemoBanner label="Engagement master · fresh 12 minutes ago" title="Engagement portfolio" description="One reconciled view of project economics, staffing and actuals." /><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Engagement</th><th>Budget</th><th>Revenue</th><th>Margin</th><th>Allocations</th><th>Status</th><th /></tr></thead><tbody>{rows.map(({ budget, calc, allocations }) => <tr key={budget.id}><td><strong>{budget.engagement}</strong><small className="table-subline">Northstar portfolio · India</small></td><td>v{budget.version}</td><td>{currency.format(budget.revenue)}</td><td>{calc.marginPercent.toFixed(1)}%</td><td>{allocations}</td><td><DemoTag tone={budget.state === "Approved" ? "good" : "warn"}>{budget.state}</DemoTag></td><td><button className="row-action" onClick={() => onSelect("ENG-02")}>Open 360 →</button></td></tr>)}</tbody></table></div></section></>;
  const budget = system.state.budgets[0]; const calc = calculateBudget(budget); const allocations = system.state.allocations.filter((item) => item.engagement === budget.engagement); const time = system.state.timesheets.filter((item) => item.engagement === budget.engagement);
  return <><DemoBanner label={`Engagement 360 · ${screen.id}`} title={budget.engagement} description="Northstar Retail · Data & AI · 02 Sep 2026–31 Mar 2027"><div className="button-cluster"><button className="secondary-button inverse" onClick={() => onSelect("BUDUI-05")}>Budget</button><button className="primary-button" onClick={() => onSelect("STFUI-01")}>Add resource</button></div></DemoBanner><section className="stat-grid"><article className="stat-card"><div><span>Approved revenue</span></div><strong>{currency.format(budget.revenue)}</strong><p>Budget v{budget.version}</p></article><article className="stat-card"><div><span>Forecast margin</span></div><strong>{calc.marginPercent.toFixed(1)}%</strong><p>Current economic signature</p></article><article className="stat-card"><div><span>Accepted allocations</span></div><strong>{allocations.length}</strong><p>{allocations.reduce((sum, item) => sum + item.allocation, 0)}% requested effort</p></article><article className="stat-card"><div><span>Approved actuals</span></div><strong>{time.filter((item) => item.state === "Approved").reduce((sum, item) => sum + item.hours.reduce((a, b) => a + b, 0), 0)}h</strong><p>{time.length} employee weeks</p></article></section><section className="detail-grid"><article className="surface workflow-section"><div className="surface-heading"><div><span className="section-kicker">{screen.title}</span><h2>Governed project record</h2></div><DemoTag tone="good">Active</DemoTag></div><dl className="workflow-dl"><div><dt>Engagement ID</dt><dd>ENG-004291</dd></div><div><dt>Project manager</dt><dd>Neha Gupta</dd></div><div><dt>Budget gate</dt><dd>{budget.state}</dd></div><div><dt>Commercial reference</dt><dd>SOW-2026-184 · Valid</dd></div><div><dt>Salesforce tower</dt><dd>Data & AI</dd></div><div><dt>Data freshness</dt><dd>12 minutes</dd></div></dl></article><aside className="surface"><div className="surface-heading"><div><span className="section-kicker">Related records</span><h2>Operational links</h2></div></div><div className="related-actions"><button onClick={() => onSelect("ENG-03")}>Resources <b>{allocations.length}</b></button><button onClick={() => onSelect("BUDUI-06")}>Budget versions <b>{budget.version}</b></button><button onClick={() => onSelect("TIMEUI-05")}>Timesheets <b>{time.length}</b></button><button onClick={() => onSelect("ENG-07")}>Risks and actions <b>2</b></button></div></aside></section></>;
}

function BudgetEditor({ budget, system, onToast }: { budget: DemoBudget; system: DemoSystem; onToast: (message: string) => void }) {
  const [draft, setDraft] = useState(budget);
  const calc = calculateBudget(draft);
  const setNumber = (key: keyof DemoBudget, value: string) => setDraft((current) => ({ ...current, [key]: Number(value) }));
  return <section className="form-layout"><article className="surface form-surface"><div className="form-heading"><span className="section-kicker">Budget assumptions · {budget.id}</span><h2>{budget.engagement}</h2><p>All totals are recalculated from inputs; display values are never treated as authoritative.</p></div><div className="field-grid">{[
    ["Revenue", "revenue"], ["Base labour", "baseLabour"], ["Uplift %", "uplift"], ["Effort contingency %", "effortContingency"], ["Expense contingency %", "expenseContingency"], ["Travel rate", "travelRate"], ["Onsite person-months", "onsiteMonths"], ["Planned hours", "plannedHours"],
  ].map(([label, key]) => <label key={key} htmlFor={`budget-${key}`}><span>{label}</span><input id={`budget-${key}`} type="number" min="0" value={String(draft[key as keyof DemoBudget])} onChange={(event) => setNumber(key as keyof DemoBudget, event.target.value)} /></label>)}</div><div className="sticky-actions"><span /><button className="secondary-button" onClick={() => setDraft(budget)}>Discard</button><button className="primary-button" onClick={() => { system.updateBudget(budget.id, draft); onToast(`${budget.id} recalculated and saved as a draft`); }}>Save calculated draft →</button></div></article><aside className="surface review-rail"><div className="surface-heading"><div><span className="section-kicker">Live calculation</span><h2>Economics</h2></div></div><dl className="calculation-list"><div><dt>Burdened labour</dt><dd>{currency.format(calc.burdenedLabour)}</dd></div><div><dt>Travel</dt><dd>{currency.format(calc.travel)}</dd></div><div><dt>Total cost</dt><dd>{currency.format(calc.totalCost)}</dd></div><div><dt>Gross margin</dt><dd>{currency.format(calc.grossMargin)}</dd></div><div><dt>Margin</dt><dd>{calc.marginPercent.toFixed(2)}%</dd></div><div><dt>Blended cost/hour</dt><dd>{currency.format(calc.blendedCost)}</dd></div></dl><div className="policy-box"><span>Approval route</span><strong>{calc.marginPercent >= 30 ? "Auto-approval eligible" : calc.marginPercent >= 25 ? "Portfolio Manager" : calc.marginPercent >= 20 ? "Portfolio Manager → HOD" : "Portfolio Manager → HOD → GM/COO"}</strong><small>Resource360 policy R360-POLICY-2.0</small></div></aside></section>;
}

function downloadText(name: string, value: string) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([value], { type: "text/csv;charset=utf-8" })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }

function BudgetRosterDemo({ budget, mode, system, onToast }: { budget: DemoBudget; mode: "grid" | "import"; system: DemoSystem; onToast: (message: string) => void }) {
  const sample = JSON.stringify([{ employeeId: "EXL-DEMO-1004", employee: "Meera Nair", role: "FSC Consultant", month: "2026-11", allocation: 50, plannedHours: 80, costRate: 3100, roleStart: "2026-11-01", roleEnd: "2027-02-28" }], null, 2);
  const [payload, setPayload] = useState(sample); const [errors, setErrors] = useState<string[]>([]); const rows = system.state.budgetRoster.filter((item) => item.budgetId === budget.id);
  const validate = () => { const next: string[] = []; try { const parsed = JSON.parse(payload) as Partial<DemoBudgetRosterLine>[]; if (!Array.isArray(parsed) || !parsed.length) next.push("At least one roster row is required."); else parsed.forEach((row, index) => { if (!row.employeeId || !row.employee || !row.role || !row.month) next.push(`Row ${index + 1}: employeeId, employee, role and month are required.`); if (!row.plannedHours || row.plannedHours <= 0) next.push(`Row ${index + 1}: plannedHours must be positive.`); if (!row.allocation || row.allocation <= 0 || row.allocation > 100) next.push(`Row ${index + 1}: allocation must be 1–100.`); if ((row.costRate ?? -1) < 0) next.push(`Row ${index + 1}: costRate cannot be negative.`); if (!row.roleStart || !row.roleEnd || row.roleEnd < row.roleStart) next.push(`Row ${index + 1}: role dates are required and must be ordered.`); }); } catch { next.push("Payload must be a valid JSON array."); } setErrors(next); return next.length === 0; };
  if (mode === "import") return <section className="form-layout"><article className="surface form-surface"><div className="form-heading"><span className="section-kicker">Atomic monthly roster import · mock</span><h2>{budget.engagement}</h2><p>Validate every row before one all-or-none browser transaction. Production uses the Apex roster import service.</p></div><label className="wide-field"><span>Sanitized JSON rows</span><textarea rows={14} value={payload} onChange={(event) => { setPayload(event.target.value); setErrors([]); }} /></label>{errors.length > 0 && <div className="workflow-warning"><span>!</span><p>{errors.join(" ")}</p></div>}<div className="sticky-actions"><span>Formula-like content and invalid governed values are rejected.</span><button className="secondary-button" onClick={() => { validate(); onToast("Roster validation completed"); }}>Validate rows</button>{errors.length > 0 && <button className="secondary-button" onClick={() => downloadText("budget-roster-errors.csv", `row,status,message\n${errors.map((item, index) => `${index + 1},INVALID,"${item.replaceAll('"', '""')}"`).join("\n")}`)}>Download errors</button>}<button className="primary-button" onClick={() => { if (!validate()) return; const parsed = JSON.parse(payload) as Omit<DemoBudgetRosterLine, "id" | "budgetId">[]; system.importBudgetRoster(budget.id, parsed); onToast(`${parsed.length} roster row(s) committed atomically`); }}>Commit import →</button></div></article><aside className="surface review-rail"><div className="surface-heading"><div><span className="section-kicker">Contract</span><h2>R360-MOCK-1.2</h2></div></div><dl className="calculation-list"><div><dt>Mode</dt><dd>Atomic</dd></div><div><dt>Maximum</dt><dd>200 rows</dd></div><div><dt>Identity</dt><dd>Employee + month + role</dd></div><div><dt>Evidence</dt><dd>Payload hash + audit</dd></div></dl></aside></section>;
  return <><DemoBanner label="Monthly resource plan · 160h standard" title={`${budget.engagement} roster grid`} description="Named or role-placeholder rows retain effective role dates, allocation percent, planned hours and rate." /><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Resource</th><th>Role</th><th>Month</th><th>Role window</th><th>Allocation</th><th>Planned</th><th>160h assurance</th><th>Planned cost</th></tr></thead><tbody>{rows.map((row) => { const expected = row.allocation * 1.6; const variance = row.plannedHours - expected; return <tr key={row.id}><td><strong>{row.employee}</strong><small>{row.employeeId}</small></td><td>{row.role}</td><td>{row.month}</td><td>{row.roleStart}–{row.roleEnd}</td><td>{row.allocation}%</td><td>{row.plannedHours}h</td><td><DemoTag tone={Math.abs(variance) < .01 ? "good" : "warn"}>{variance === 0 ? "Reconciled" : `${variance > 0 ? "+" : ""}${variance}h`}</DemoTag></td><td>{currency.format(row.plannedHours * row.costRate)}</td></tr>; })}</tbody></table></div></section></>;
}

export function BudgetDemo({ screen, system, onSelect, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  const target = screen.id === "BUDUI-02" || screen.id === "BUDUI-08" ? system.state.budgets.find((item) => item.state === "Draft") ?? system.state.budgets[0] : screen.id === "BUDUI-09" || screen.id === "BUDUI-10" ? system.state.budgets.find((item) => item.state === "Pending approval") ?? system.state.budgets[0] : system.state.budgets[0];
  if (screen.id === "BUDUI-02") return <BudgetEditor budget={target} system={system} onToast={onToast} />;
  if (screen.id === "BUDUI-04") return <BudgetRosterDemo budget={target} mode="grid" system={system} onToast={onToast} />;
  if (screen.id === "BUDUI-11") return <BudgetRosterDemo budget={target} mode="import" system={system} onToast={onToast} />;
  if (screen.id === "BUDUI-01") return <><DemoBanner label="Budget service · calculated demo" title="Project budgets" description="Draft, submit, approve and compare immutable economic versions." ><button className="primary-button" onClick={() => onSelect("BUDUI-02")}>Open draft editor</button></DemoBanner><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Engagement</th><th>Version</th><th>Revenue</th><th>Total cost</th><th>Margin</th><th>State</th><th /></tr></thead><tbody>{system.state.budgets.map((budget) => { const calc = calculateBudget(budget); return <tr key={budget.id}><td><strong>{budget.engagement}</strong><small className="table-subline">{budget.id}</small></td><td>v{budget.version}</td><td>{currency.format(budget.revenue)}</td><td>{currency.format(calc.totalCost)}</td><td>{calc.marginPercent.toFixed(1)}%</td><td><DemoTag tone={budget.state === "Approved" ? "good" : budget.state === "Rejected" ? "bad" : "warn"}>{budget.state}</DemoTag></td><td><button className="row-action" onClick={() => onSelect(budget.state === "Pending approval" ? "BUDUI-10" : "BUDUI-05")}>Open →</button></td></tr>; })}</tbody></table></div></section></>;
  const calc = calculateBudget(target);
  if (screen.id === "BUDUI-08") return <section className="decision-layout surface"><div><span className="section-kicker">Submit and route</span><h2>{target.engagement} · Budget v{target.version}</h2><p>Server-parity calculations have passed the static demo validation suite.</p><div className="decision-summary"><span>Revenue<strong>{currency.format(target.revenue)}</strong></span><span>Total cost<strong>{currency.format(calc.totalCost)}</strong></span><span>Margin<strong>{calc.marginPercent.toFixed(2)}%</strong></span><span>Route<strong>{calc.marginPercent >= 30 ? "Auto-approval" : "Configured chain"}</strong></span></div><div className="confirmation-check"><input type="checkbox" id="budget-submit-confirm" aria-labelledby="budget-submit-label" /><span id="budget-submit-label"><strong>I confirm the assumptions and calculated economics.</strong><small>The demo records actor, role, policy and time.</small></span></div><button className="primary-button" onClick={() => { system.submitBudget(target.id); onToast(`${target.id} submitted for approval`); onSelect("BUDUI-09"); }}>Submit calculated version →</button></div></section>;
  if (screen.id === "BUDUI-09" || screen.id === "BUDUI-10") return <><DemoBanner label="Budget approval checkpoint" title={target.state === "Pending approval" ? `${target.engagement} requires a decision` : "No pending budget at this level"} description={`Budget v${target.version} · ${calc.marginPercent.toFixed(2)}% margin · active role ${system.state.activeRole}`} /><section className="detail-grid"><article className="surface workflow-section"><div className="surface-heading"><div><span className="section-kicker">Read-only submitted version</span><h2>Economic decision context</h2></div><DemoTag tone={target.state === "Pending approval" ? "warn" : "good"}>{target.state}</DemoTag></div><dl className="workflow-dl"><div><dt>Revenue</dt><dd>{currency.format(target.revenue)}</dd></div><div><dt>Burdened labour</dt><dd>{currency.format(calc.burdenedLabour)}</dd></div><div><dt>Travel</dt><dd>{currency.format(calc.travel)}</dd></div><div><dt>Total cost</dt><dd>{currency.format(calc.totalCost)}</dd></div><div><dt>Gross margin</dt><dd>{currency.format(calc.grossMargin)}</dd></div><div><dt>Margin</dt><dd>{calc.marginPercent.toFixed(2)}%</dd></div></dl></article><aside className="surface decision-sidebar"><span className="section-kicker">Attributable decision</span><h2>Budget approval</h2><textarea id="budget-decision-note" aria-label="Budget decision note" rows={4} placeholder="Decision note..." /><div><button className="secondary-button danger" disabled={target.state !== "Pending approval"} onClick={() => { system.decideBudget(target.id, "Rejected", "Economics require revision"); onToast(`${target.id} rejected`); }}>Reject</button><button className="primary-button" disabled={target.state !== "Pending approval"} onClick={() => { system.decideBudget(target.id, "Approved", "Economics and delivery assumptions validated"); onToast(`${target.id} approved`); }}>Approve budget</button></div></aside></section></>;
  const phases = [["Discover", "Sep", "Oct", "1,120h"], ["Build", "Nov", "Jan", "6,840h"], ["Deploy", "Feb", "Mar", "3,720h"]];
  return <><DemoBanner label={`${screen.id} · ${target.state}`} title={screen.title} description={`${target.engagement} · Budget v${target.version} · R360-POLICY-2.0`}><button className="primary-button" onClick={() => onSelect(target.state === "Draft" ? "BUDUI-08" : "BUDUI-06")}>{target.state === "Draft" ? "Submit version" : "View versions"}</button></DemoBanner><section className="stat-grid"><article className="stat-card"><div><span>Revenue</span></div><strong>{currency.format(target.revenue)}</strong><p>Engagement currency INR</p></article><article className="stat-card"><div><span>Total cost</span></div><strong>{currency.format(calc.totalCost)}</strong><p>Labour + travel</p></article><article className="stat-card"><div><span>Gross margin</span></div><strong>{currency.format(calc.grossMargin)}</strong><p>{calc.marginPercent.toFixed(2)}%</p></article><article className="stat-card"><div><span>Planned effort</span></div><strong>{target.plannedHours.toLocaleString("en-IN")}h</strong><p>{phases.length} phases</p></article></section><section className="surface data-surface"><div className="surface-heading"><div><span className="section-kicker">Reconciled plan</span><h2>Phase and WBS summary</h2></div><DemoTag tone="good">Balanced</DemoTag></div><div className="responsive-table"><table><thead><tr><th>Phase</th><th>Start</th><th>End</th><th>Effort</th><th>State</th></tr></thead><tbody>{phases.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}<td><DemoTag tone="good">Valid</DemoTag></td></tr>)}</tbody></table></div></section></>;
}

function ClaimForm({ system, onToast }: { system: DemoSystem; onToast: (message: string) => void }) {
  const [capability, setCapability] = useState("Agentforce"); const [level, setLevel] = useState<1 | 2 | 3 | 4>(2); const [evidence, setEvidence] = useState("Agentforce Launch sandbox implementation and design review");
  return <section className="surface form-surface"><div className="form-heading"><span className="section-kicker">Governed capability claim</span><h2>Add Salesforce capability</h2><p>A submitted claim remains pending and cannot influence staffing until manager approval.</p></div><div className="field-grid"><label htmlFor="claim-capability"><span>Capability</span><input id="claim-capability" value={capability} onChange={(event) => setCapability(event.target.value)} /></label><label htmlFor="claim-level"><span>Requested level</span><select id="claim-level" value={level} onChange={(event) => setLevel(Number(event.target.value) as 1 | 2 | 3 | 4)}>{levelNames.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></label><label className="wide-field" htmlFor="claim-evidence"><span>Evidence</span><textarea id="claim-evidence" value={evidence} onChange={(event) => setEvidence(event.target.value)} rows={4} /></label></div><div className="sticky-actions"><span /><button className="primary-button" disabled={!capability.trim() || evidence.trim().length < 10} onClick={() => { system.submitClaim("EXL-013884", capability, level, evidence); onToast(`${capability} claim submitted for manager review`); }}>Submit claim →</button></div></section>;
}

export function SkillsDemo({ screen, system, onSelect, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  const [query, setQuery] = useState("Data Cloud");
  const results = useMemo(() => system.state.people.map((person) => ({ person, fit: fitForPerson(person, query) })).sort((a, b) => b.fit - a.fit), [query, system.state.people]);
  if (screen.id === "SKLUI-10" || screen.id === "SKLUI-11") return <ClaimForm system={system} onToast={onToast} />;
  if (screen.id === "SKLUI-14" || screen.id === "SKLUI-15") { const pending = system.state.claims.filter((item) => item.state === "Pending"); return <><DemoBanner label="Manager review queue" title="Capability claims" description="Claimant evidence remains immutable; the reviewer may approve, adjust or reject." />{pending.length ? <section className="surface operational-list">{pending.map((claim) => { const person = system.state.people.find((item) => item.id === claim.personId)!; return <article className="claim-review" key={claim.id}><span className="record-avatar person">{person.initials}</span><div><strong>{person.name} · {claim.capability}</strong><small>Requested {levelNames[claim.requestedLevel - 1]} · {claim.submittedAt}</small><p>{claim.evidence}</p></div><div><button className="secondary-button danger" onClick={() => { system.decideClaim(claim.id, "Rejected", claim.requestedLevel, "Additional project evidence required"); onToast(`${claim.id} rejected with an actionable reason`); }}>Reject</button><button className="primary-button" onClick={() => { system.decideClaim(claim.id, "Approved", claim.requestedLevel, "Evidence meets the proficiency descriptor"); onToast(`${claim.id} approved`); }}>Approve claim</button></div></article>; })}</section> : <EmptyState title="No pending claims" detail="New practitioner claims will appear here." action="Add demo claim" onAction={() => onSelect("SKLUI-10")} />}</>; }
  if (screen.id === "SKLUI-16" || screen.id === "SKLUI-17") return <><DemoBanner label="Explainable talent discovery" title="Salesforce capability search" description="Mandatory employment and credential gates are applied before the ranked demo score." /><section className="surface talent-search"><div className="filter-bar"><label className="inline-search"><span>⌕</span><input aria-label="Required capability" value={query} onChange={(event) => setQuery(event.target.value)} /></label><button className="filter-button">Minimum · Advanced</button><button className="filter-button">Credential · Active</button><span className="filter-spacer" /><button className="secondary-button" onClick={() => onSelect("STFUI-13")}>Add top candidate to request</button></div><div className="candidate-grid">{results.map(({ person, fit }) => <article key={person.id}><div><span className="record-avatar person">{person.initials}</span><span><strong>{person.name}</strong><small>{person.title} · {person.location}</small></span><b>{fit}% fit</b></div><div className="fit-meter"><i style={{ width: `${fit}%` }} /></div><ul>{person.skills.slice(0, 3).map((skill) => <li key={skill.name}><span>{skill.name}</span><b>{levelNames[skill.level - 1]}</b></li>)}</ul><footer><DemoTag tone={person.credentials.some((item) => item.state === "Verified") ? "good" : "warn"}>{person.credentials[0]?.state ?? "No credential"}</DemoTag><span>{person.availability}% available</span></footer></article>)}</div></section></>;
  const person = system.state.people[0];
  return <><DemoBanner label={`${screen.id} · governed profile`} title={screen.id === "SKLUI-01" ? "My skills and credentials" : screen.title} description="People Master particulars remain read-only; approved capabilities and verified credentials retain source and freshness."><button className="primary-button" onClick={() => onSelect("SKLUI-10")}>Add capability</button></DemoBanner><section className="detail-grid"><article className="surface workflow-section"><div className="record-banner compact"><div className="record-avatar person">{person.initials}</div><div className="record-title"><span>{person.id}</span><h2>{person.name}</h2><p>{person.title} · {person.location}</p></div><DemoTag tone="good">Profile ready</DemoTag></div><div className="profile-capabilities"><h3>Approved capabilities</h3>{person.skills.map((skill) => <div key={skill.name}><span><strong>{skill.name}</strong><small>Last used {skill.lastUsed}</small></span><b>{levelNames[skill.level - 1]}</b></div>)}</div></article><aside className="surface"><div className="surface-heading"><div><span className="section-kicker">Credential gateway</span><h2>Verified credentials</h2></div></div><div className="credential-list">{person.credentials.map((item) => <div key={item.name}><span>◇</span><span><strong>{item.name}</strong><small>Verified {item.verifiedAt}</small></span><DemoTag tone={item.state === "Verified" ? "good" : "warn"}>{item.state}</DemoTag></div>)}</div><button className="link-button full" onClick={() => onSelect("SKLUI-14")}>Open manager review queue →</button></aside></section></>;
}

export function StaffingPlanningDemo({ screen, system, onSelect, onCreate, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onCreate: (request: StaffingRequest) => void; onToast: (message: string) => void }) {
  const capability = screen.id === "STFUI-06" || screen.id === "STFUI-07" ? "MuleSoft" : "Data Cloud";
  const candidates = system.state.people.map((person) => ({ person, fit: fitForPerson(person, capability) })).sort((a, b) => b.fit - a.fit);
  const candidate = capability === "MuleSoft" ? system.state.people.find((item) => item.name === "Kabir Rao")! : system.state.people[0];
  const draftRequest: StaffingRequest = { id: `SR-D${new Date().getDate()}${new Date().getMonth() + 1}`, candidate: candidate.name, initials: candidate.initials, role: candidate.title, engagement: capability === "MuleSoft" ? "Integration Factory" : "Global Retail Cloud", account: capability === "MuleSoft" ? "Fabrikam" : "Northstar Retail", location: `${candidate.location} · Hybrid`, startDate: "02 Sep 2026", endDate: "31 Mar 2027", allocation: 40, fit: fitForPerson(candidate, capability), status: "Awaiting decision", priority: "High", ageHours: 0, slaHours: 72, budgetCoverage: capability === "MuleSoft" ? 96 : 100, margin: capability === "MuleSoft" ? 24.9 : 31.2, capacityAvailable: candidate.availability, requestedBy: "Maya Patel", staffer: "COE Staffing Pool", requirements: [`${capability} · Advanced`, "Active mandatory credential", "40% availability"], fitEvidence: candidate.skills.map((item) => `${item.name} · ${levelNames[item.level - 1]}`), warnings: capability === "MuleSoft" ? ["Budget coverage is 96%; Staffer sees this warning."] : [], history: [{ label: "Draft prepared", detail: "Current session · Maya Patel" }] };
  if (screen.id === "STFUI-13" || screen.id === "STFUI-14") return <><DemoBanner label="Staffing request checkpoint" title={`${draftRequest.role} · ${draftRequest.engagement}`} description="The request is soft demand until a Staffer accepts it; committed capacity and timesheet eligibility remain unchanged." /><section className="detail-grid"><article className="surface workflow-section"><div className="surface-heading"><div><span className="section-kicker">Review before submit</span><h2>Candidate, capacity and budget</h2></div><strong className="large-fit">{draftRequest.fit}% fit</strong></div><dl className="workflow-dl"><div><dt>Candidate</dt><dd>{draftRequest.candidate}</dd></div><div><dt>Role</dt><dd>{draftRequest.role}</dd></div><div><dt>Dates</dt><dd>{draftRequest.startDate}–{draftRequest.endDate}</dd></div><div><dt>Requested effort</dt><dd>{draftRequest.allocation}%</dd></div><div><dt>Available capacity</dt><dd>{draftRequest.capacityAvailable}%</dd></div><div><dt>Budget coverage</dt><dd>{draftRequest.budgetCoverage}%</dd></div></dl>{draftRequest.warnings.map((warning) => <div className="workflow-warning" key={warning}><span>!</span><p>{warning}</p></div>)}</article><aside className="surface decision-sidebar"><span className="section-kicker">Explicit submission</span><h2>Create soft request</h2><p>The demo records request ID, actor, active role and current policy.</p><div className="confirmation-check"><input type="checkbox" id="staffing-submit-confirm" defaultChecked aria-labelledby="staffing-submit-label" /><span id="staffing-submit-label"><strong>Budget and candidate evidence reviewed</strong><small>Staffer will revalidate at decision time.</small></span></div><button className="primary-button" onClick={() => { onCreate(draftRequest); onToast(`${draftRequest.id} created and routed to the Staffer queue`); onSelect("STFUI-21"); }}>Submit staffing request →</button></aside></section></>;
  return <><DemoBanner label={`${screen.id} · skills-aware staffing`} title={screen.title} description={`Requirement: ${capability} · Advanced · active credential · 40% capacity`}><button className="primary-button" onClick={() => onSelect("STFUI-13")}>Review request</button></DemoBanner><section className="surface talent-search"><div className="filter-bar"><button className="filter-button">02 Sep 2026–31 Mar 2027</button><button className="filter-button">India · Hybrid</button><button className="filter-button">Rank mode</button><span className="filter-spacer" /><DemoTag tone="good">Budget checked</DemoTag></div><div className="candidate-grid">{candidates.map(({ person, fit }) => { const availabilityStatus = person.availability >= 40 ? "Eligible" : person.availability > 0 ? "Partially available" : "Unavailable"; return <article key={person.id}><div><span className="record-avatar person">{person.initials}</span><span><strong>{person.name}</strong><small>{person.title}</small></span><b>{fit}%</b></div><div className="fit-meter"><i style={{ width: `${fit}%` }} /></div><ul><li><span>Capacity</span><b>{person.availability}%</b></li><li><span>Mandatory credential</span><b>{person.credentials.some((item) => item.state === "Verified") ? "Pass" : "Review"}</b></li><li><span>Gap reason</span><b>{person.availability < 40 ? `Needs ${40 - person.availability}% more capacity` : "Hard gates passed"}</b></li></ul><footer><DemoTag tone={availabilityStatus === "Eligible" ? "good" : availabilityStatus === "Unavailable" ? "bad" : "warn"}>{availabilityStatus}</DemoTag><button className="link-button" onClick={() => onSelect("STFUI-13")}>Select →</button></footer></article>; })}</div></section></>;
}

export function TimesheetDemo({ screen, system, onToast }: { screen: ScreenSpec; system: DemoSystem; onToast: (message: string) => void }) {
  if (screen.id === "TIMEUI-08") { const exceptions = system.state.timesheets.map((sheet) => ({ ...sheet, total: sheet.hours.reduce((sum, value) => sum + value, 0), reason: sheet.state === "Submitted" ? "Decision overdue" : sheet.hours.reduce((sum, value) => sum + value, 0) < 40 ? "Incomplete week" : "No exception", owner: sheet.state === "Submitted" ? "Reporting Manager" : sheet.employee })).filter((item) => item.reason !== "No exception"); return <><DemoBanner label="Mock reconciliation · weekly actuals" title="Timesheet compliance and exceptions" description="Missing, late, pending and plan-variance rows keep an accountable owner and drill path." /><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Timesheet</th><th>Employee</th><th>Week</th><th>Hours</th><th>State</th><th>Exception</th><th>Owner</th></tr></thead><tbody>{exceptions.map((item) => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.employee}</td><td>{item.week}</td><td>{item.total}h</td><td>{item.state}</td><td><DemoTag tone="warn">{item.reason}</DemoTag></td><td>{item.owner}</td></tr>)}</tbody></table></div></section></>; }
  const sheet = system.state.timesheets.find((item) => item.state === "Draft") ?? system.state.timesheets[0];
  if (!sheet) return <EmptyState title="No eligible timesheet" detail="An accepted allocation creates date-and-role eligibility." />;
  const allocation = system.state.allocations.find((item) => item.id === sheet.allocationId);
  const total = sheet.hours.reduce((sum, value) => sum + value, 0);
  const isManager = screen.id === "TIMEUI-04" || screen.id === "TIMEUI-05" || screen.id === "TIMEUI-06";
  return <><DemoBanner label={`${screen.id} · allocation-aware actuals`} title={isManager ? "Team timesheet decision" : `${sheet.employee} · ${sheet.week}`} description={`${sheet.engagement} · ${allocation?.role ?? "Accepted role"} · ${sheet.state}`}><DemoTag tone={sheet.state === "Approved" ? "good" : sheet.state === "Rejected" ? "bad" : "warn"}>{sheet.state}</DemoTag></DemoBanner><section className="surface timesheet-workspace"><div className="surface-heading"><div><span className="section-kicker">Accepted allocation · {sheet.allocationId}</span><h2>{sheet.engagement}</h2></div><strong>{total}h</strong></div><div className="time-grid"><span>Work unit</span>{["Mon 24", "Tue 25", "Wed 26", "Thu 27", "Fri 28", "Sat 29", "Sun 30"].map((day) => <b key={day}>{day}</b>)}<strong>Total</strong><span><strong>Delivery</strong><small>{allocation?.role}</small></span>{sheet.hours.map((hours, index) => <label key={index}><span className="sr-only">Hours for day {index + 1}</span><input type="number" min="0" max="24" step="0.25" value={hours} disabled={sheet.state !== "Draft"} onChange={(event) => system.updateTimesheet(sheet.id, index, Number(event.target.value))} /></label>)}<strong>{total}h</strong></div><div className="timesheet-controls"><span><i className={total === 40 ? "good" : "warn"}>{total === 40 ? "✓" : "!"}</i><span><strong>{total === 40 ? "Week is complete" : `${40 - total} hours remaining`}</strong><small>Entries are eligible under {sheet.allocationId}.</small></span></span><div>{isManager ? <><button className="secondary-button danger" disabled={sheet.state !== "Submitted"} onClick={() => { system.decideTimesheet(sheet.id, "Rejected", "Correct project attribution"); onToast(`${sheet.id} rejected for correction`); }}>Reject</button><button className="primary-button" disabled={sheet.state !== "Submitted"} onClick={() => { system.decideTimesheet(sheet.id, "Approved", "Allocation and work unit validated"); onToast(`${sheet.id} approved`); }}>Approve week</button></> : <button className="primary-button" disabled={sheet.state !== "Draft" || total === 0} onClick={() => { system.submitTimesheet(sheet.id); onToast(`${sheet.id} submitted for manager review`); }}>Submit week →</button>}</div></div></section></>;
}

export function CommandDemo({ screen, system, onSelect }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void }) {
  const approvedRevenue = system.state.budgets.filter((item) => item.state === "Approved").reduce((sum, item) => sum + item.revenue, 0);
  const actualHours = system.state.timesheets.filter((item) => item.state === "Approved").reduce((sum, item) => sum + item.hours.reduce((a, b) => a + b, 0), 0);
  return <><DemoBanner label={`${screen.id} · certified demo cutoff 22 Aug 2026 12:15 IST`} title={screen.title} description="Every KPI exposes its population, cutoff and drill path; values update from the browser transaction ledger." /><section className="stat-grid"><article className="stat-card"><div><span>Approved revenue</span></div><strong>{currency.format(approvedRevenue)}</strong><p>Current approved signatures</p></article><article className="stat-card"><div><span>Accepted allocations</span></div><strong>{system.state.allocations.length}</strong><p>Committed capacity only</p></article><article className="stat-card"><div><span>Approved actuals</span></div><strong>{actualHours}h</strong><p>Submitted time excluded</p></article><article className="stat-card"><div><span>Audit events</span></div><strong>{system.state.audit.length}</strong><p>Current demo ledger</p></article></section><section className="dashboard-grid"><article className="surface chart-panel large-chart"><div className="surface-heading"><div><span className="section-kicker">Effective-dated allocation</span><h2>Capacity by practitioner</h2></div></div><div className="horizontal-bars">{system.state.people.map((person) => { const committed = system.state.allocations.filter((item) => item.employee === person.name).reduce((sum, item) => sum + item.allocation, 0); return <button key={person.id} onClick={() => onSelect("SKLUI-05")}><span>{person.name}</span><i><b style={{ width: `${committed}%` }} /></i><strong>{committed}%</strong></button>; })}</div></article><article className="surface"><div className="surface-heading"><div><span className="section-kicker">Decision quality</span><h2>Control status</h2></div></div><div className="control-status"><p><DemoTag tone="good">Fresh</DemoTag><span>People Master</span><b>12m</b></p><p><DemoTag tone="good">Reconciled</DemoTag><span>Budget service</span><b>Live</b></p><p><DemoTag tone="good">Current</DemoTag><span>Staffing ledger</span><b>Live</b></p><p><DemoTag tone="warn">Pending</DemoTag><span>Timesheet approvals</span><b>{system.state.timesheets.filter((item) => item.state === "Submitted").length}</b></p></div></article></section></>;
}

export function AdminDemo({ screen, system, onSelect, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  const [draft,setDraft]=useState({domain:"Policy",code:"Staffing_Expiry_Hours",label:"Staffing request SLA",value:"72",unit:"hours",effectiveFrom:new Date().toISOString().slice(0,10),reason:"Governed EXL Salesforce COE configuration change."});
  const [previewed,setPreviewed]=useState(false);
  if (screen.id === "ADMUI-01") {
    const routes = { IDENTITY_SSO: "ADMUI-03", INTEGRATIONS: "ADMUI-07", FICTIONAL_DATA: "ADMUI-08", LEGAL_APPROVALS: "ADMUI-07", OPERATIONS: "CMD-08" } as const;
    const passed = system.state.activationPillars.filter((item) => item.state === "Passed").length;
    return <>
      <DemoBanner label="ADMUI-01 · sanitized activation rehearsal" title="Demo Activation Center" description="Exercise the five external production domains as deterministic, auditable simulations. No EXL endpoint, credential, identity, approval or production record is used.">
        <div className="button-cluster"><DemoTag tone={passed === 5 ? "good" : "warn"}>{passed === 5 ? "5/5 passed" : "Ready to run"}</DemoTag><button className="secondary-button inverse" onClick={() => { const id = system.runDemoActivation(); onToast(`${id} passed all five sanitized activation simulations`); }}>Run complete demo activation</button></div>
      </DemoBanner>
      <section className="activation-grid" aria-label="Demo activation simulations">{system.state.activationPillars.map((pillar, index) => <article className="surface activation-card" key={pillar.id}><header><span>{String(index + 1).padStart(2, "0")}</span><DemoTag tone={pillar.state === "Passed" ? "good" : "neutral"}>{pillar.state}</DemoTag></header><h2>{pillar.label}</h2><p>{pillar.simulation}</p><dl><div><dt>Evidence</dt><dd>{pillar.evidence}</dd></div><div><dt>Mock owner</dt><dd>{pillar.owner}</dd></div>{pillar.lastEvidence && <div><dt>Last passed</dt><dd>{pillar.lastEvidence}</dd></div>}</dl><button className="link-button" onClick={() => onSelect(routes[pillar.id])}>Open evidence →</button></article>)}</section>
      <section className="surface data-surface activation-approvals"><div className="surface-heading"><div><span className="section-kicker">Fictional decision register</span><h2>Legal, risk and business approval evidence</h2></div><DemoTag tone="good">6 approved mock</DemoTag></div><div className="responsive-table"><table><thead><tr><th>Decision</th><th>Mock owner</th><th>Evidence reference</th><th>Decision date</th><th>Status</th></tr></thead><tbody>{system.state.approvalEvidence.map((item) => <tr key={item.id}><td><strong>{item.decision}</strong></td><td>{item.owner}</td><td>{item.evidenceReference}</td><td>{item.decidedOn}</td><td><DemoTag tone="good">{item.status}</DemoTag></td></tr>)}</tbody></table></div></section>
      <section className="detail-grid activation-summary"><article className="surface"><div className="surface-heading"><div><span className="section-kicker">Latest rehearsal</span><h2>{system.state.activationRun ? system.state.activationRun.id : "No run recorded yet"}</h2></div>{system.state.activationRun && <DemoTag tone="good">{system.state.activationRun.state}</DemoTag>}</div>{system.state.activationRun ? <dl className="workflow-dl"><div><dt>Completed</dt><dd>{system.state.activationRun.completedAt}</dd></div><div><dt>Checks</dt><dd>{system.state.activationRun.checksPassed}/{system.state.activationRun.checksTotal}</dd></div><div><dt>Boundary</dt><dd>{system.state.activationRun.boundary}</dd></div><div><dt>External calls</dt><dd>0</dd></div></dl> : <EmptyState title="Activation rehearsal is ready" detail="Run the complete demo activation to create attributable evidence in the local audit ledger." />}</article><aside className="surface review-rail"><div className="surface-heading"><div><span className="section-kicker">Safety contract</span><h2>What this run guarantees</h2></div></div><ul className="check-list"><li className="pass"><i>✓</i><span><strong>Fictional identities and records</strong><small>No EXL employee or customer data</small></span></li><li className="pass"><i>✓</i><span><strong>No credential collection</strong><small>SSO and group claims are simulated</small></span></li><li className="pass"><i>✓</i><span><strong>No destructive disposition</strong><small>Retention, backup and restore are rehearsals</small></span></li><li className="pass"><i>✓</i><span><strong>Attributable evidence</strong><small>Actions enter the immutable demo ledger</small></span></li></ul></aside></section>
    </>;
  }
  if (screen.id === "ADMUI-02" || screen.id === "ADMUI-03") return <><DemoBanner label="R360-MOCK-ACTIVATION-2026-08-24" title={screen.id === "ADMUI-02" ? "People, roles and effective access" : "Role-permission and Entra mapping matrix"} description="Eighteen approved mock personas map business authority to a least-privilege Salesforce assignment, an environment-owned Entra group alias, scope and segregation class."><DemoTag tone="good">18 mappings approved</DemoTag></DemoBanner><section className="surface data-surface"><div className="surface-heading"><div><span className="section-kicker">Effective-dated access contract</span><h2>Persona assignment matrix</h2></div><span>Delegation requires an attributable user, reason and validity window</span></div><div className="responsive-table"><table><thead><tr><th>Business role</th><th>Permission assignment</th><th>Entra group alias</th><th>Scope</th><th>Decision authority</th><th>SoD class</th><th>Delegation</th><th>Status</th></tr></thead><tbody>{system.state.personas.map((persona)=><tr key={persona.id}><td><strong>{persona.role}</strong><small className="table-subline">{persona.owner}</small></td><td>{persona.permissionSetGroup}</td><td>{persona.entraGroupAlias}</td><td>{persona.scope}</td><td>{persona.authority}</td><td>{persona.segregation}</td><td>{persona.delegationAllowed?"Effective-dated":"Not allowed"}</td><td><DemoTag tone="good">Approved mock</DemoTag></td></tr>)}</tbody></table></div></section></>;
  if (screen.id === "ADMUI-07") return <><DemoBanner label="R360-MOCK-1.2 · approved mock authority and lineage" title="Source, identity and retention assurance" description="Every system of record, stable identity, canonical field contract, owner, direction and freshness gate is deployable Salesforce metadata. No production EXL connector is implied."><button className="secondary-button inverse" onClick={() => { system.runRetentionDryRun(); onToast("Eight approved mock retention rules evaluated; no records deleted"); }}>Run retention assurance</button></DemoBanner><section className="source-contract-grid">{system.state.sourceContracts.map((source) => <article className="surface" key={source.id}><div className="surface-heading"><div><span className="section-kicker">{source.contractVersion} · {source.direction}</span><h2>{source.source}</h2></div><DemoTag tone={source.state === "Fresh" || source.state === "Native" ? "good" : "warn"}>{source.state}</DemoTag></div><dl className="workflow-dl"><div><dt>Entity / identity</dt><dd>{source.entity} · {source.identity}</dd></div><div><dt>Canonical fields</dt><dd>{source.canonicalFields}</dd></div><div><dt>Owner / gate</dt><dd>{source.owner} · {source.blocking?"Fail closed":"Advisory"}</dd></div><div><dt>Cadence</dt><dd>{source.cadenceHours===0?"Transactional":`${source.cadenceHours}h`}</dd></div><div><dt>Completeness</dt><dd>{source.completeness}%</dd></div><div><dt>Changes / collisions</dt><dd>{source.inserted} inserted · {source.updated} updated · {source.collisions} collisions</dd></div><div><dt>Cutoff</dt><dd>{source.cutoff}</dd></div><div><dt>Decision</dt><dd>{source.approvalStatus}</dd></div></dl><button className="primary-button" disabled={source.direction === "Native"} onClick={() => { system.runMockReconciliation(source.id); onToast(`${source.source} reconciled under ${source.contractVersion}`); }}>{source.direction === "Native" ? "Native transaction lineage" : "Run mock reconciliation"}</button></article>)}</section><section className="surface data-surface"><div className="surface-heading"><div><span className="section-kicker">ADM-003 · non-destructive execution</span><h2>Approved mock retention schedule</h2></div><DemoTag tone="good">8 rules</DemoTag></div><div className="responsive-table"><table><thead><tr><th>Category</th><th>Retention</th><th>Disposition contract</th><th>Recovery</th><th>Legal hold</th><th>Owner</th><th>Status</th></tr></thead><tbody>{system.state.retentionRules.map((rule)=><tr key={rule.id}><td><strong>{rule.category}</strong></td><td>{rule.retentionDays.toLocaleString("en-IN")} days</td><td>{rule.action}</td><td>{rule.recoveryDays} days</td><td>{rule.legalHoldEligible?"Eligible":"Not applicable"}</td><td>{rule.owner}</td><td><DemoTag tone="good">Approved mock</DemoTag></td></tr>)}</tbody></table></div></section></>;
  if (screen.id === "ADMUI-08") return <><DemoBanner label="Controlled batch evidence" title="Import, retry and correlation operations" description="Each governed source run exposes contract version, processed changes, collisions, completeness and retry state without retaining raw sensitive payloads."><button className="secondary-button inverse" onClick={()=>onToast("Exact sanitized row-error report prepared")}>Download row errors</button></DemoBanner><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Contract</th><th>Entity</th><th>Direction</th><th>Cutoff</th><th>Processed changes</th><th>Collisions</th><th>Completeness</th><th>State</th><th>Action</th></tr></thead><tbody>{system.state.sourceContracts.filter((source)=>source.direction!=="Native").map((source)=><tr key={source.id}><td><strong>{source.id}</strong><small className="table-subline">{source.contractVersion}</small></td><td>{source.entity}</td><td>{source.direction}</td><td>{source.cutoff}</td><td>{source.inserted+source.updated}</td><td>{source.collisions}</td><td>{source.completeness}%</td><td><DemoTag tone={source.state==="Fresh"?"good":"warn"}>{source.state}</DemoTag></td><td><button className="link-button" onClick={()=>{system.runMockReconciliation(source.id);onToast(`${source.id} retry/reconciliation completed`);}}>Reconcile →</button></td></tr>)}</tbody></table></div></section></>;
  if (screen.id === "CMD-09") return <><DemoBanner label="Immutable browser demo ledger" title="Audit and operations" description="Every demo decision records actor, active role, entity, timestamp and attributable detail."><button className="secondary-button inverse" onClick={() => onToast("Sanitized audit export prepared in the demo")}>Export sanitized log</button></DemoBanner><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Actor</th><th>Active role</th><th>Detail</th></tr></thead><tbody>{system.state.audit.map((item) => <tr key={item.id}><td>{item.time}</td><td><strong>{item.action}</strong></td><td>{item.entity}</td><td>{item.actor}</td><td>{item.role}</td><td>{item.detail}</td></tr>)}</tbody></table></div></section></>;
  const set=(key:string,value:string)=>{setDraft((current)=>({...current,[key]:value}));setPreviewed(false);};
  const save=()=>{if(!previewed){onToast("Preview and validate the configuration before saving");return;}const id=system.saveConfiguration(draft);onToast(`${id} saved as a validated draft`);};
  return <><DemoBanner label={`${screen.id} · governed browser demo`} title={screen.title} description="The Salesforce build uses the same draft → preview → independent approval → active/rollback lifecycle. Browser changes below are sanitized and local only." />
    <section className="admin-grid">{[["Governed defaults",149,"Current"],["Runtime versions",system.state.configurations.length,"Audited"],["Permission groups",17,"Healthy"],["Persona mappings",system.state.personas.length,"Approved"],["Source lineages",system.state.sourceContracts.length,"Approved"],["Retention rules",system.state.retentionRules.length,"Dry-run"]].map(([label,count,status])=><button className="admin-card" key={String(label)} onClick={()=>onToast(`${label} is represented in the governed demo baseline`)}><span>⚙</span><div><strong>{label}</strong><small>{count} configured</small></div><DemoTag tone="good">{String(status)}</DemoTag><b>→</b></button>)}</section>
    <section className="surface release-bundle"><div className="surface-heading"><div><span className="section-kicker">Atomic configuration bundle</span><h2>EXL-MOCK-2026-09-R1</h2></div><DemoTag tone={system.state.configurations.some((item)=>item.releaseKey==="EXL-MOCK-2026-09-R1"&&item.state==="Pending approval")?"warn":system.state.configurations.filter((item)=>item.releaseKey==="EXL-MOCK-2026-09-R1").every((item)=>item.state==="Active")?"good":"neutral"}>{system.state.configurations.find((item)=>item.releaseKey==="EXL-MOCK-2026-09-R1")?.state??"Draft"}</DemoTag></div><p>Two settings share one effective date and are previewed, submitted and decided as a single transaction.</p><div className="release-items">{system.state.configurations.filter((item)=>item.releaseKey==="EXL-MOCK-2026-09-R1").map((item)=><span key={item.id}><strong>{item.code}</strong><small>{item.value} {item.unit} · {item.effectiveFrom}</small></span>)}</div><div className="sticky-actions"><span>Production Salesforce enforces independent submitter and approver identities.</span><button className="secondary-button" onClick={()=>{system.submitConfigurationRelease("EXL-MOCK-2026-09-R1");onToast("Atomic release submitted with cross-setting validation");}}>Submit release</button><button className="primary-button" onClick={()=>{system.decideConfigurationRelease("EXL-MOCK-2026-09-R1",true,"Independent mock control approval");onToast("Atomic release activated in the local demo ledger");}}>Approve release</button></div></section>
    <section className="form-layout configuration-demo"><article className="surface form-surface"><div className="form-heading"><span className="section-kicker">Configuration operator</span><h2>Draft and impact preview</h2><p>Secrets, endpoints, schema and permissions are deliberately excluded from business configuration.</p></div><div className="field-grid"><label><span>Domain</span><select value={draft.domain} onChange={(event)=>set("domain",event.target.value)}>{["Policy","Delivery Role","Classification","General LOV","Approval","Escalation","Notification","Integration","KPI"].map((value)=><option key={value}>{value}</option>)}</select></label><label><span>Stable code</span><input value={draft.code} onChange={(event)=>set("code",event.target.value)} /></label><label className="wide-field"><span>Display label</span><input value={draft.label} onChange={(event)=>set("label",event.target.value)} /></label><label><span>Proposed value</span><input value={draft.value} onChange={(event)=>set("value",event.target.value)} /></label><label><span>Unit</span><input value={draft.unit} onChange={(event)=>set("unit",event.target.value)} /></label><label><span>Effective from</span><input type="date" value={draft.effectiveFrom} onChange={(event)=>set("effectiveFrom",event.target.value)} /></label><label className="wide-field"><span>Required change reason</span><textarea rows={3} value={draft.reason} onChange={(event)=>set("reason",event.target.value)} /></label></div>{previewed&&<div className="configuration-preview"><DemoTag tone={draft.code&&draft.value&&draft.reason?"good":"bad"}>{draft.code&&draft.value&&draft.reason?"Ready to save":"Blocked"}</DemoTag><span><strong>Impact</strong><small>Staffing SLA, expiry controls, metrics and future decisions · current value compared · safe numeric bounds passed</small></span></div>}<div className="sticky-actions"><span>Operator cannot activate its own draft.</span><button className="secondary-button" onClick={()=>setPreviewed(true)}>Preview impact</button><button className="primary-button" disabled={!previewed||!draft.code||!draft.value||!draft.reason} onClick={save}>Save draft →</button></div></article><aside className="surface review-rail"><div className="surface-heading"><div><span className="section-kicker">Control boundary</span><h2>Separation of duties</h2></div></div><dl className="calculation-list"><div><dt>Operator</dt><dd>Draft + submit</dd></div><div><dt>Approver</dt><dd>Activate + rollback</dd></div><div><dt>Auditor</dt><dd>Read evidence</dd></div><div><dt>Secrets</dt><dd>External Credentials only</dd></div></dl></aside></section>
    <section className="surface config-surface"><div className="surface-heading"><div><span className="section-kicker">Effective-dated catalog</span><h2>Representative runtime versions</h2></div><button className="secondary-button danger" onClick={()=>{system.reset();onToast("All browser demo data restored to its signed baseline");}}>Reset demo</button></div><div className="config-list"><div className="config-row head"><span>Configuration</span><span>Domain</span><span>Effective</span><span>State</span><span>Version</span><span>Action</span></div>{system.state.configurations.map((item)=><div className="config-row" key={item.id}><span><strong>{item.label}</strong><small>{item.code} · {item.value}{item.unit?` ${item.unit}`:""}</small></span><span>{item.domain}</span><span>{item.effectiveFrom}</span><DemoTag tone={item.state==="Active"?"good":item.state==="Rejected"?"bad":"warn"}>{item.state}</DemoTag><span>v{item.version}</span><span className="configuration-actions">{item.state==="Draft"&&<button onClick={()=>{system.submitConfiguration(item.id);onToast(`${item.id} submitted for approval`);}}>Submit</button>}{item.state==="Pending approval"&&<><button onClick={()=>{system.decideConfiguration(item.id,true,"Independent control approval");onToast(`${item.id} activated`);}}>Approve</button><button onClick={()=>{system.decideConfiguration(item.id,false,"Requires correction");onToast(`${item.id} rejected`);}}>Reject</button></>}{["Active","Retired"].includes(item.state)&&<button onClick={()=>{system.restoreConfiguration(item.id);onToast(`${item.id} restored as a new active version`);}}>Restore</button>}</span></div>)}</div></section></>;
}

export function ScenarioDemo({ system, onToast }: { system: DemoSystem; onToast: (message: string) => void }) {
  const [draft, setDraft] = useState({ name: "Data Cloud demand surge", startDate: "2026-09-01", endDate: "2026-12-31", headcountDelta: 6, billableAllocation: 75 }); const businessDays = 88; const capacityHours = draft.headcountDelta * 8 * businessDays; const billableHours = capacityHours * draft.billableAllocation / 100;
  return <><DemoBanner label="AIUI-03 · deterministic mock only" title="What-if capacity planner" description="Model isolated demand, capacity and billing mix without changing staffing, budgets or allocations." /><section className="form-layout"><article className="surface form-surface"><div className="field-grid"><label className="wide-field"><span>Scenario name</span><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label><span>Start</span><input type="date" value={draft.startDate} onChange={(event) => setDraft({ ...draft, startDate: event.target.value })} /></label><label><span>End</span><input type="date" value={draft.endDate} onChange={(event) => setDraft({ ...draft, endDate: event.target.value })} /></label><label><span>Headcount delta</span><input type="number" value={draft.headcountDelta} onChange={(event) => setDraft({ ...draft, headcountDelta: Number(event.target.value) })} /></label><label><span>Billable allocation %</span><input type="number" min="0" max="100" value={draft.billableAllocation} onChange={(event) => setDraft({ ...draft, billableAllocation: Number(event.target.value) })} /></label></div><div className="sticky-actions"><span>No governed record is mutated.</span><button className="primary-button" onClick={() => { const id = system.saveScenario({ ...draft, capacityHours, billableHours }); onToast(`${id} saved to the local mock scenario ledger`); }}>Save scenario →</button></div></article><aside className="surface review-rail"><div className="surface-heading"><div><span className="section-kicker">Scenario output</span><h2>Capacity impact</h2></div></div><dl className="calculation-list"><div><dt>Business days</dt><dd>{businessDays}</dd></div><div><dt>Capacity</dt><dd>{capacityHours.toLocaleString("en-IN")}h</dd></div><div><dt>Billable hours</dt><dd>{billableHours.toLocaleString("en-IN")}h</dd></div><div><dt>Guardrail</dt><dd>{draft.billableAllocation >= 75 ? "At target" : "Below 75% target"}</dd></div></dl><p className="ai-disclaimer">Monday–Friday mock calendar. Production holidays, milestones and commercial dependencies require activated source contracts.</p></aside></section>{system.state.scenarios.length > 0 && <section className="surface data-surface"><div className="surface-heading"><div><span className="section-kicker">Saved local scenarios</span><h2>Comparison ledger</h2></div></div><div className="responsive-table"><table><thead><tr><th>Scenario</th><th>Dates</th><th>HC delta</th><th>Capacity</th><th>Billable</th><th>Saved</th></tr></thead><tbody>{system.state.scenarios.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small className="table-subline">{item.id}</small></td><td>{item.startDate}–{item.endDate}</td><td>{item.headcountDelta}</td><td>{item.capacityHours}h</td><td>{item.billableHours}h</td><td>{item.savedAt}</td></tr>)}</tbody></table></div></section>}</>;
}
