import { useMemo, useState } from "react";
import { calculateBudget, fitForPerson, type DemoBudget, type DemoRole, type DemoSystem } from "./demo-system";
import type { ScreenSpec } from "./screen-data";
import type { StaffingRequest } from "./staffing-workflow";

const levelNames = ["Beginner", "Intermediate", "Advanced", "SME"];
const roles: DemoRole[] = ["Practitioner", "Reporting Manager", "Project Manager", "COE Staffer", "Budget Approver", "Administrator"];
const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

function DemoTag({ children, tone = "neutral" }: { children: string; tone?: "good" | "warn" | "bad" | "neutral" }) {
  return <span className={`status-pill ${tone}`}><i />{children}</span>;
}

function DemoBanner({ label, title, description, children }: { label: string; title: string; description: string; children?: React.ReactNode }) {
  return <section className="demo-section-banner"><div><span>{label}</span><h2>{title}</h2><p>{description}</p></div>{children}</section>;
}

function EmptyState({ title, detail, action, onAction }: { title: string; detail: string; action?: string; onAction?: () => void }) {
  return <div className="operational-empty"><span>◇</span><strong>{title}</strong><p>{detail}</p>{action && <button className="primary-button" onClick={onAction}>{action}</button>}</div>;
}

export function DemoHome({ system, onSelect }: { system: DemoSystem; onSelect: (id: string) => void }) {
  const approved = system.state.budgets.filter((item) => item.state === "Approved").length;
  const pendingClaims = system.state.claims.filter((item) => item.state === "Pending").length;
  const submittedTime = system.state.timesheets.filter((item) => item.state === "Submitted").length;
  return <>
    <DemoBanner label="Production-quality static demo" title={`Welcome, Maya · ${system.state.activeRole}`} description="Complete the governed path using sanitized browser data. Every decision updates notifications and the immutable demo audit stream."><button className="secondary-button inverse" onClick={() => onSelect("GLB-05")}>Switch role</button></DemoBanner>
    <section className="stat-grid"><article className="stat-card"><div><span>Approved budgets</span></div><strong>{approved}</strong><p><b>✓</b> Staffing-gate ready</p></article><article className="stat-card"><div><span>Accepted allocations</span></div><strong>{system.state.allocations.length}</strong><p><b>↗</b> Effective-dated demo lines</p></article><article className="stat-card"><div><span>Pending skill reviews</span></div><strong>{pendingClaims}</strong><p><b>!</b> Manager action</p></article><article className="stat-card"><div><span>Submitted timesheets</span></div><strong>{submittedTime}</strong><p><b>•</b> Awaiting decision</p></article></section>
    <section className="surface golden-path"><div className="surface-heading"><div><span className="section-kicker">R1 golden path</span><h2>Run the complete demo workflow</h2></div><DemoTag tone="good">Operational</DemoTag></div><div className="path-steps">{[
      ["1", "Approve a project budget", "Validate calculated economics and approval routing.", "BUDUI-09"],
      ["2", "Review capability supply", "Inspect skills, credentials and candidate fit.", "SKLUI-17"],
      ["3", "Create a staffing request", "Submit a budget-covered candidate request.", "STFUI-13"],
      ["4", "Make the Staffer decision", "Commit capacity through a human checkpoint.", "STFUI-21"],
      ["5", "Submit and approve time", "Use the accepted allocation for eligible actuals.", "TIMEUI-01"],
    ].map(([number, title, detail, id]) => <button key={id} onClick={() => onSelect(id)}><i>{number}</i><span><strong>{title}</strong><small>{detail}</small></span><b>→</b></button>)}</div></section>
  </>;
}

export function NotificationDemo({ system, onSelect }: { system: DemoSystem; onSelect: (id: string) => void }) {
  return <section className="surface operational-list"><div className="surface-heading"><div><span className="section-kicker">Actionable inbox</span><h2>Notifications</h2></div><button className="secondary-button" onClick={system.markNotificationsRead}>Mark all read</button></div>{system.state.notifications.length ? system.state.notifications.map((item) => <button className={item.read ? "read" : ""} key={item.id} onClick={() => onSelect(item.title.includes("Budget") ? "BUDUI-09" : item.title.includes("Capability") ? "SKLUI-14" : "STFUI-21")}><span className={`notification-severity ${item.severity.toLowerCase()}`}>!</span><span><strong>{item.title}</strong><small>{item.detail}</small></span><time>{item.time}</time><DemoTag tone={item.read ? "neutral" : "warn"}>{item.read ? "Read" : "Unread"}</DemoTag><b>→</b></button>) : <EmptyState title="Inbox is clear" detail="Decision, compliance and data-quality events will appear here." />}</section>;
}

export function RoleDemo({ system, onSelect, onToast }: { system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  return <section className="surface role-workspace"><div className="form-heading"><span className="section-kicker">Demo identity and scope</span><h2>Choose an active business role</h2><p>The static demo changes navigation context and attributes every subsequent audit event to this role.</p></div><div className="role-grid">{roles.map((role) => <button className={system.state.activeRole === role ? "active" : ""} key={role} onClick={() => system.setRole(role)}><i>{role.slice(0, 2).toUpperCase()}</i><span><strong>{role}</strong><small>Salesforce COE · India</small></span>{system.state.activeRole === role && <b>Active</b>}</button>)}</div><div className="sticky-actions"><span /><button className="primary-button" onClick={() => { onToast(`Active role changed to ${system.state.activeRole}`); onSelect("GLB-02"); }}>Apply role and scope →</button></div></section>;
}

export function EngagementDemo({ screen, system, onSelect }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void }) {
  const rows = system.state.budgets.map((budget) => {
    const calc = calculateBudget(budget);
    const allocations = system.state.allocations.filter((item) => item.engagement === budget.engagement).length;
    return { budget, calc, allocations };
  });
  if (screen.id === "ENG-01") return <><DemoBanner label="Engagement master · fresh 12 minutes ago" title="Engagement portfolio" description="One reconciled view of project economics, staffing and actuals." /><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Engagement</th><th>Budget</th><th>Revenue</th><th>Margin</th><th>Allocations</th><th>Status</th><th /></tr></thead><tbody>{rows.map(({ budget, calc, allocations }) => <tr key={budget.id}><td><strong>{budget.engagement}</strong><small className="table-subline">Northstar portfolio · India</small></td><td>v{budget.version}</td><td>{currency.format(budget.revenue)}</td><td>{calc.marginPercent.toFixed(1)}%</td><td>{allocations}</td><td><DemoTag tone={budget.state === "Approved" ? "good" : "warn"}>{budget.state}</DemoTag></td><td><button className="row-action" onClick={() => onSelect("ENG-02")}>Open 360 →</button></td></tr>)}</tbody></table></div></section></>;
  const budget = system.state.budgets[0]; const calc = calculateBudget(budget); const allocations = system.state.allocations.filter((item) => item.engagement === budget.engagement); const time = system.state.timesheets.filter((item) => item.engagement === budget.engagement);
  return <><DemoBanner label={`Engagement 360 · ${screen.id}`} title={budget.engagement} description="Northstar Retail · Data & AI · 02 Sep 2026–31 Mar 2027"><div className="button-cluster"><button className="secondary-button inverse" onClick={() => onSelect("BUDUI-05")}>Budget</button><button className="primary-button" onClick={() => onSelect("STFUI-01")}>Add resource</button></div></DemoBanner><section className="stat-grid"><article className="stat-card"><div><span>Approved revenue</span></div><strong>{currency.format(budget.revenue)}</strong><p>Budget v{budget.version}</p></article><article className="stat-card"><div><span>Forecast margin</span></div><strong>{calc.marginPercent.toFixed(1)}%</strong><p>Current economic signature</p></article><article className="stat-card"><div><span>Accepted allocations</span></div><strong>{allocations.length}</strong><p>{allocations.reduce((sum, item) => sum + item.allocation, 0)}% requested effort</p></article><article className="stat-card"><div><span>Approved actuals</span></div><strong>{time.filter((item) => item.state === "Approved").reduce((sum, item) => sum + item.hours.reduce((a, b) => a + b, 0), 0)}h</strong><p>{time.length} employee weeks</p></article></section><section className="detail-grid"><article className="surface workflow-section"><div className="surface-heading"><div><span className="section-kicker">{screen.title}</span><h2>Governed project record</h2></div><DemoTag tone="good">Active</DemoTag></div><dl className="workflow-dl"><div><dt>Engagement ID</dt><dd>ENG-004291</dd></div><div><dt>Project manager</dt><dd>Neha Gupta</dd></div><div><dt>Budget gate</dt><dd>{budget.state}</dd></div><div><dt>Commercial reference</dt><dd>SOW-2026-184 · Valid</dd></div><div><dt>Salesforce tower</dt><dd>Data & AI</dd></div><div><dt>Data freshness</dt><dd>12 minutes</dd></div></dl></article><aside className="surface"><div className="surface-heading"><div><span className="section-kicker">Related records</span><h2>Operational links</h2></div></div><div className="related-actions"><button onClick={() => onSelect("ENG-03")}>Resources <b>{allocations.length}</b></button><button onClick={() => onSelect("BUDUI-06")}>Budget versions <b>{budget.version}</b></button><button onClick={() => onSelect("TIMEUI-05")}>Timesheets <b>{time.length}</b></button><button onClick={() => onSelect("ENG-07")}>Risks and actions <b>2</b></button></div></aside></section></>;
}

function BudgetEditor({ budget, system, onToast }: { budget: DemoBudget; system: DemoSystem; onToast: (message: string) => void }) {
  const [draft, setDraft] = useState(budget);
  const calc = calculateBudget(draft);
  const setNumber = (key: keyof DemoBudget, value: string) => setDraft((current) => ({ ...current, [key]: Number(value) }));
  return <section className="form-layout"><article className="surface form-surface"><div className="form-heading"><span className="section-kicker">Budget assumptions · {budget.id}</span><h2>{budget.engagement}</h2><p>All totals are recalculated from inputs; display values are never treated as authoritative.</p></div><div className="field-grid">{[
    ["Revenue", "revenue"], ["Base labour", "baseLabour"], ["Uplift %", "uplift"], ["Effort contingency %", "effortContingency"], ["Expense contingency %", "expenseContingency"], ["Travel rate", "travelRate"], ["Onsite person-months", "onsiteMonths"], ["Planned hours", "plannedHours"],
  ].map(([label, key]) => <label key={key} htmlFor={`budget-${key}`}><span>{label}</span><input id={`budget-${key}`} type="number" min="0" value={String(draft[key as keyof DemoBudget])} onChange={(event) => setNumber(key as keyof DemoBudget, event.target.value)} /></label>)}</div><div className="sticky-actions"><span /><button className="secondary-button" onClick={() => setDraft(budget)}>Discard</button><button className="primary-button" onClick={() => { system.updateBudget(budget.id, draft); onToast(`${budget.id} recalculated and saved as a draft`); }}>Save calculated draft →</button></div></article><aside className="surface review-rail"><div className="surface-heading"><div><span className="section-kicker">Live calculation</span><h2>Economics</h2></div></div><dl className="calculation-list"><div><dt>Burdened labour</dt><dd>{currency.format(calc.burdenedLabour)}</dd></div><div><dt>Travel</dt><dd>{currency.format(calc.travel)}</dd></div><div><dt>Total cost</dt><dd>{currency.format(calc.totalCost)}</dd></div><div><dt>Gross margin</dt><dd>{currency.format(calc.grossMargin)}</dd></div><div><dt>Margin</dt><dd>{calc.marginPercent.toFixed(2)}%</dd></div><div><dt>Blended cost/hour</dt><dd>{currency.format(calc.blendedCost)}</dd></div></dl><div className="policy-box"><span>Approval route</span><strong>{calc.marginPercent >= 30 ? "Auto-approval eligible" : calc.marginPercent >= 25 ? "Portfolio Manager" : calc.marginPercent >= 20 ? "Portfolio Manager → HOD" : "Portfolio Manager → HOD → GM/COO"}</strong><small>Resource360 margin policy v1.0</small></div></aside></section>;
}

export function BudgetDemo({ screen, system, onSelect, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  const target = screen.id === "BUDUI-02" || screen.id === "BUDUI-08" ? system.state.budgets.find((item) => item.state === "Draft") ?? system.state.budgets[0] : screen.id === "BUDUI-09" || screen.id === "BUDUI-10" ? system.state.budgets.find((item) => item.state === "Pending approval") ?? system.state.budgets[0] : system.state.budgets[0];
  if (screen.id === "BUDUI-02") return <BudgetEditor budget={target} system={system} onToast={onToast} />;
  if (screen.id === "BUDUI-01") return <><DemoBanner label="Budget service · calculated demo" title="Project budgets" description="Draft, submit, approve and compare immutable economic versions." ><button className="primary-button" onClick={() => onSelect("BUDUI-02")}>Open draft editor</button></DemoBanner><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Engagement</th><th>Version</th><th>Revenue</th><th>Total cost</th><th>Margin</th><th>State</th><th /></tr></thead><tbody>{system.state.budgets.map((budget) => { const calc = calculateBudget(budget); return <tr key={budget.id}><td><strong>{budget.engagement}</strong><small className="table-subline">{budget.id}</small></td><td>v{budget.version}</td><td>{currency.format(budget.revenue)}</td><td>{currency.format(calc.totalCost)}</td><td>{calc.marginPercent.toFixed(1)}%</td><td><DemoTag tone={budget.state === "Approved" ? "good" : budget.state === "Rejected" ? "bad" : "warn"}>{budget.state}</DemoTag></td><td><button className="row-action" onClick={() => onSelect(budget.state === "Pending approval" ? "BUDUI-10" : "BUDUI-05")}>Open →</button></td></tr>; })}</tbody></table></div></section></>;
  const calc = calculateBudget(target);
  if (screen.id === "BUDUI-08") return <section className="decision-layout surface"><div><span className="section-kicker">Submit and route</span><h2>{target.engagement} · Budget v{target.version}</h2><p>Server-parity calculations have passed the static demo validation suite.</p><div className="decision-summary"><span>Revenue<strong>{currency.format(target.revenue)}</strong></span><span>Total cost<strong>{currency.format(calc.totalCost)}</strong></span><span>Margin<strong>{calc.marginPercent.toFixed(2)}%</strong></span><span>Route<strong>{calc.marginPercent >= 30 ? "Auto-approval" : "Configured chain"}</strong></span></div><div className="confirmation-check"><input type="checkbox" id="budget-submit-confirm" aria-labelledby="budget-submit-label" /><span id="budget-submit-label"><strong>I confirm the assumptions and calculated economics.</strong><small>The demo records actor, role, policy and time.</small></span></div><button className="primary-button" onClick={() => { system.submitBudget(target.id); onToast(`${target.id} submitted for approval`); onSelect("BUDUI-09"); }}>Submit calculated version →</button></div></section>;
  if (screen.id === "BUDUI-09" || screen.id === "BUDUI-10") return <><DemoBanner label="Budget approval checkpoint" title={target.state === "Pending approval" ? `${target.engagement} requires a decision` : "No pending budget at this level"} description={`Budget v${target.version} · ${calc.marginPercent.toFixed(2)}% margin · active role ${system.state.activeRole}`} /><section className="detail-grid"><article className="surface workflow-section"><div className="surface-heading"><div><span className="section-kicker">Read-only submitted version</span><h2>Economic decision context</h2></div><DemoTag tone={target.state === "Pending approval" ? "warn" : "good"}>{target.state}</DemoTag></div><dl className="workflow-dl"><div><dt>Revenue</dt><dd>{currency.format(target.revenue)}</dd></div><div><dt>Burdened labour</dt><dd>{currency.format(calc.burdenedLabour)}</dd></div><div><dt>Travel</dt><dd>{currency.format(calc.travel)}</dd></div><div><dt>Total cost</dt><dd>{currency.format(calc.totalCost)}</dd></div><div><dt>Gross margin</dt><dd>{currency.format(calc.grossMargin)}</dd></div><div><dt>Margin</dt><dd>{calc.marginPercent.toFixed(2)}%</dd></div></dl></article><aside className="surface decision-sidebar"><span className="section-kicker">Attributable decision</span><h2>Budget approval</h2><textarea id="budget-decision-note" aria-label="Budget decision note" rows={4} placeholder="Decision note..." /><div><button className="secondary-button danger" disabled={target.state !== "Pending approval"} onClick={() => { system.decideBudget(target.id, "Rejected", "Economics require revision"); onToast(`${target.id} rejected`); }}>Reject</button><button className="primary-button" disabled={target.state !== "Pending approval"} onClick={() => { system.decideBudget(target.id, "Approved", "Economics and delivery assumptions validated"); onToast(`${target.id} approved`); }}>Approve budget</button></div></aside></section></>;
  const phases = [["Discover", "Sep", "Oct", "1,120h"], ["Build", "Nov", "Jan", "6,840h"], ["Deploy", "Feb", "Mar", "3,720h"]];
  return <><DemoBanner label={`${screen.id} · ${target.state}`} title={screen.title} description={`${target.engagement} · Budget v${target.version} · calculated at policy v1.0`}><button className="primary-button" onClick={() => onSelect(target.state === "Draft" ? "BUDUI-08" : "BUDUI-06")}>{target.state === "Draft" ? "Submit version" : "View versions"}</button></DemoBanner><section className="stat-grid"><article className="stat-card"><div><span>Revenue</span></div><strong>{currency.format(target.revenue)}</strong><p>Engagement currency INR</p></article><article className="stat-card"><div><span>Total cost</span></div><strong>{currency.format(calc.totalCost)}</strong><p>Labour + travel</p></article><article className="stat-card"><div><span>Gross margin</span></div><strong>{currency.format(calc.grossMargin)}</strong><p>{calc.marginPercent.toFixed(2)}%</p></article><article className="stat-card"><div><span>Planned effort</span></div><strong>{target.plannedHours.toLocaleString("en-IN")}h</strong><p>{phases.length} phases</p></article></section><section className="surface data-surface"><div className="surface-heading"><div><span className="section-kicker">Reconciled plan</span><h2>Phase and WBS summary</h2></div><DemoTag tone="good">Balanced</DemoTag></div><div className="responsive-table"><table><thead><tr><th>Phase</th><th>Start</th><th>End</th><th>Effort</th><th>State</th></tr></thead><tbody>{phases.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}<td><DemoTag tone="good">Valid</DemoTag></td></tr>)}</tbody></table></div></section></>;
}

function ClaimForm({ system, onToast }: { system: DemoSystem; onToast: (message: string) => void }) {
  const [capability, setCapability] = useState("Agentforce"); const [level, setLevel] = useState<1 | 2 | 3 | 4>(2); const [evidence, setEvidence] = useState("Agentforce Launch sandbox implementation and design review");
  return <section className="surface form-surface"><div className="form-heading"><span className="section-kicker">Governed capability claim</span><h2>Add Salesforce capability</h2><p>A submitted claim remains pending and cannot influence staffing until manager approval.</p></div><div className="field-grid"><label htmlFor="claim-capability"><span>Capability</span><input id="claim-capability" value={capability} onChange={(event) => setCapability(event.target.value)} /></label><label htmlFor="claim-level"><span>Requested level</span><select id="claim-level" value={level} onChange={(event) => setLevel(Number(event.target.value) as 1 | 2 | 3 | 4)}>{levelNames.map((name, index) => <option key={name} value={index + 1}>{name}</option>)}</select></label><label className="wide-field" htmlFor="claim-evidence"><span>Evidence</span><textarea id="claim-evidence" value={evidence} onChange={(event) => setEvidence(event.target.value)} rows={4} /></label></div><div className="sticky-actions"><span /><button className="primary-button" disabled={!capability.trim() || evidence.trim().length < 10} onClick={() => { system.submitClaim("EXL-013884", capability, level, evidence); onToast(`${capability} claim submitted for manager review`); }}>Submit claim →</button></div></section>;
}

export function SkillsDemo({ screen, system, onSelect, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onToast: (message: string) => void }) {
  const [query, setQuery] = useState("Data Cloud");
  const results = useMemo(() => system.state.people.map((person) => ({ person, fit: fitForPerson(person, query) })).sort((a, b) => b.fit - a.fit), [query, system.state.people]);
  if (screen.id === "SKLUI-10" || screen.id === "SKLUI-11") return <ClaimForm system={system} onToast={onToast} />;
  if (screen.id === "SKLUI-14" || screen.id === "SKLUI-15") { const pending = system.state.claims.filter((item) => item.state === "Pending"); return <><DemoBanner label="Manager review queue" title="Capability claims" description="Claimant evidence remains immutable; the reviewer may approve, adjust or reject." />{pending.length ? <section className="surface operational-list">{pending.map((claim) => { const person = system.state.people.find((item) => item.id === claim.personId)!; return <article className="claim-review" key={claim.id}><span className="record-avatar person">{person.initials}</span><div><strong>{person.name} · {claim.capability}</strong><small>Requested {levelNames[claim.requestedLevel - 1]} · {claim.submittedAt}</small><p>{claim.evidence}</p></div><div><button className="secondary-button danger" onClick={() => { system.decideClaim(claim.id, "Rejected", claim.requestedLevel, "Additional project evidence required"); onToast(`${claim.id} rejected with an actionable reason`); }}>Reject</button><button className="primary-button" onClick={() => { system.decideClaim(claim.id, "Approved", claim.requestedLevel, "Evidence meets the proficiency descriptor"); onToast(`${claim.id} approved`); }}>Approve claim</button></div></article>; })}</section> : <EmptyState title="No pending claims" detail="New practitioner claims will appear here." action="Add demo claim" onAction={() => onSelect("SKLUI-10")} />}</>; }
  if (screen.id === "SKLUI-16" || screen.id === "SKLUI-17") return <><DemoBanner label="Explainable talent discovery" title="Salesforce capability search" description="Mandatory employment and credential gates are applied before the ranked demo score." /><section className="surface talent-search"><div className="filter-bar"><label className="inline-search"><span>⌕</span><input aria-label="Required capability" value={query} onChange={(event) => setQuery(event.target.value)} /></label><button className="filter-button">Minimum · Advanced</button><button className="filter-button">Credential · Active</button><span className="filter-spacer" /><button className="secondary-button" onClick={() => onSelect("STFUI-13")}>Add top candidate to request</button></div><div className="candidate-grid">{results.map(({ person, fit }) => <article key={person.id}><div><span className="record-avatar person">{person.initials}</span><span><strong>{person.name}</strong><small>{person.title} · {person.location}</small></span><b>{fit}% fit</b></div><div className="fit-meter"><i style={{ width: `${fit}%` }} /></div><ul>{person.skills.slice(0, 3).map((skill) => <li key={skill.name}><span>{skill.name}</span><b>{levelNames[skill.level - 1]}</b></li>)}</ul><footer><DemoTag tone={person.credentials.some((item) => item.state === "Verified") ? "good" : "warn"}>{person.credentials[0]?.state ?? "No credential"}</DemoTag><span>{person.availability}% available</span></footer></article>)}</div></section></>;
  const person = system.state.people[0];
  return <><DemoBanner label={`${screen.id} · governed profile`} title={screen.id === "SKLUI-01" ? "My skills and credentials" : screen.title} description="People Master particulars remain read-only; approved capabilities and verified credentials retain source and freshness."><button className="primary-button" onClick={() => onSelect("SKLUI-10")}>Add capability</button></DemoBanner><section className="detail-grid"><article className="surface workflow-section"><div className="record-banner compact"><div className="record-avatar person">{person.initials}</div><div className="record-title"><span>{person.id}</span><h2>{person.name}</h2><p>{person.title} · {person.location}</p></div><DemoTag tone="good">Profile ready</DemoTag></div><div className="profile-capabilities"><h3>Approved capabilities</h3>{person.skills.map((skill) => <div key={skill.name}><span><strong>{skill.name}</strong><small>Last used {skill.lastUsed}</small></span><b>{levelNames[skill.level - 1]}</b></div>)}</div></article><aside className="surface"><div className="surface-heading"><div><span className="section-kicker">Credential gateway</span><h2>Verified credentials</h2></div></div><div className="credential-list">{person.credentials.map((item) => <div key={item.name}><span>◇</span><span><strong>{item.name}</strong><small>Verified {item.verifiedAt}</small></span><DemoTag tone={item.state === "Verified" ? "good" : "warn"}>{item.state}</DemoTag></div>)}</div><button className="link-button full" onClick={() => onSelect("SKLUI-14")}>Open manager review queue →</button></aside></section></>;
}

export function StaffingPlanningDemo({ screen, system, onSelect, onCreate, onToast }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void; onCreate: (request: StaffingRequest) => void; onToast: (message: string) => void }) {
  const capability = screen.id === "STFUI-06" || screen.id === "STFUI-07" ? "MuleSoft" : "Data Cloud";
  const candidates = system.state.people.map((person) => ({ person, fit: fitForPerson(person, capability) })).sort((a, b) => b.fit - a.fit);
  const candidate = capability === "MuleSoft" ? system.state.people.find((item) => item.name === "Kabir Rao")! : system.state.people[0];
  const draftRequest: StaffingRequest = { id: `SR-D${new Date().getDate()}${new Date().getMonth() + 1}`, candidate: candidate.name, initials: candidate.initials, role: candidate.title, engagement: capability === "MuleSoft" ? "Integration Factory" : "Global Retail Cloud", account: capability === "MuleSoft" ? "Fabrikam" : "Northstar Retail", location: `${candidate.location} · Hybrid`, startDate: "02 Sep 2026", endDate: "31 Mar 2027", allocation: 40, fit: fitForPerson(candidate, capability), status: "Awaiting decision", priority: "High", ageHours: 0, slaHours: 72, budgetCoverage: capability === "MuleSoft" ? 96 : 100, margin: capability === "MuleSoft" ? 24.9 : 31.2, capacityAvailable: candidate.availability, requestedBy: "Maya Patel", staffer: "COE Staffing Pool", requirements: [`${capability} · Advanced`, "Active mandatory credential", "40% availability"], fitEvidence: candidate.skills.map((item) => `${item.name} · ${levelNames[item.level - 1]}`), warnings: capability === "MuleSoft" ? ["Budget coverage is 96%; Staffer sees this warning."] : [], history: [{ label: "Draft prepared", detail: "Current session · Maya Patel" }] };
  if (screen.id === "STFUI-13" || screen.id === "STFUI-14") return <><DemoBanner label="Staffing request checkpoint" title={`${draftRequest.role} · ${draftRequest.engagement}`} description="The request is soft demand until a Staffer accepts it; committed capacity and timesheet eligibility remain unchanged." /><section className="detail-grid"><article className="surface workflow-section"><div className="surface-heading"><div><span className="section-kicker">Review before submit</span><h2>Candidate, capacity and budget</h2></div><strong className="large-fit">{draftRequest.fit}% fit</strong></div><dl className="workflow-dl"><div><dt>Candidate</dt><dd>{draftRequest.candidate}</dd></div><div><dt>Role</dt><dd>{draftRequest.role}</dd></div><div><dt>Dates</dt><dd>{draftRequest.startDate}–{draftRequest.endDate}</dd></div><div><dt>Requested effort</dt><dd>{draftRequest.allocation}%</dd></div><div><dt>Available capacity</dt><dd>{draftRequest.capacityAvailable}%</dd></div><div><dt>Budget coverage</dt><dd>{draftRequest.budgetCoverage}%</dd></div></dl>{draftRequest.warnings.map((warning) => <div className="workflow-warning" key={warning}><span>!</span><p>{warning}</p></div>)}</article><aside className="surface decision-sidebar"><span className="section-kicker">Explicit submission</span><h2>Create soft request</h2><p>The demo records request ID, actor, active role and current policy.</p><div className="confirmation-check"><input type="checkbox" id="staffing-submit-confirm" defaultChecked aria-labelledby="staffing-submit-label" /><span id="staffing-submit-label"><strong>Budget and candidate evidence reviewed</strong><small>Staffer will revalidate at decision time.</small></span></div><button className="primary-button" onClick={() => { onCreate(draftRequest); onToast(`${draftRequest.id} created and routed to the Staffer queue`); onSelect("STFUI-21"); }}>Submit staffing request →</button></aside></section></>;
  return <><DemoBanner label={`${screen.id} · skills-aware staffing`} title={screen.title} description={`Requirement: ${capability} · Advanced · active credential · 40% capacity`}><button className="primary-button" onClick={() => onSelect("STFUI-13")}>Review request</button></DemoBanner><section className="surface talent-search"><div className="filter-bar"><button className="filter-button">02 Sep 2026–31 Mar 2027</button><button className="filter-button">India · Hybrid</button><button className="filter-button">Rank mode</button><span className="filter-spacer" /><DemoTag tone="good">Budget checked</DemoTag></div><div className="candidate-grid">{candidates.map(({ person, fit }) => <article key={person.id}><div><span className="record-avatar person">{person.initials}</span><span><strong>{person.name}</strong><small>{person.title}</small></span><b>{fit}%</b></div><div className="fit-meter"><i style={{ width: `${fit}%` }} /></div><ul><li><span>Capacity</span><b>{person.availability}%</b></li><li><span>Mandatory credential</span><b>{person.credentials.some((item) => item.state === "Verified") ? "Pass" : "Review"}</b></li></ul><footer><span>{person.location}</span><button className="link-button" onClick={() => onSelect("STFUI-13")}>Select →</button></footer></article>)}</div></section></>;
}

export function TimesheetDemo({ screen, system, onToast }: { screen: ScreenSpec; system: DemoSystem; onToast: (message: string) => void }) {
  const sheet = system.state.timesheets.find((item) => item.state === "Draft") ?? system.state.timesheets[0];
  if (!sheet) return <EmptyState title="No eligible timesheet" detail="An accepted allocation creates date-and-role eligibility." />;
  const allocation = system.state.allocations.find((item) => item.id === sheet.allocationId);
  const total = sheet.hours.reduce((sum, value) => sum + value, 0);
  const isManager = screen.id === "TIMEUI-04" || screen.id === "TIMEUI-05" || screen.id === "TIMEUI-06";
  return <><DemoBanner label={`${screen.id} · allocation-aware actuals`} title={isManager ? "Team timesheet decision" : `${sheet.employee} · ${sheet.week}`} description={`${sheet.engagement} · ${allocation?.role ?? "Accepted role"} · ${sheet.state}`}><DemoTag tone={sheet.state === "Approved" ? "good" : sheet.state === "Rejected" ? "bad" : "warn"}>{sheet.state}</DemoTag></DemoBanner><section className="surface timesheet-workspace"><div className="surface-heading"><div><span className="section-kicker">Accepted allocation · {sheet.allocationId}</span><h2>{sheet.engagement}</h2></div><strong>{total}h</strong></div><div className="time-grid"><span>Work unit</span>{["Mon 24", "Tue 25", "Wed 26", "Thu 27", "Fri 28", "Sat 29", "Sun 30"].map((day) => <b key={day}>{day}</b>)}<strong>Total</strong><span><strong>Delivery</strong><small>{allocation?.role}</small></span>{sheet.hours.map((hours, index) => <label key={index}><span className="sr-only">Hours for day {index + 1}</span><input type="number" min="0" max="24" step="0.25" value={hours} disabled={sheet.state !== "Draft"} onChange={(event) => system.updateTimesheet(sheet.id, index, Number(event.target.value))} /></label>)}<strong>{total}h</strong></div><div className="timesheet-controls"><span><i className={total === 40 ? "good" : "warn"}>{total === 40 ? "✓" : "!"}</i><span><strong>{total === 40 ? "Week is complete" : `${40 - total} hours remaining`}</strong><small>Entries are eligible under {sheet.allocationId}.</small></span></span><div>{isManager ? <><button className="secondary-button danger" disabled={sheet.state !== "Submitted"} onClick={() => { system.decideTimesheet(sheet.id, "Rejected", "Correct project attribution"); onToast(`${sheet.id} rejected for correction`); }}>Reject</button><button className="primary-button" disabled={sheet.state !== "Submitted"} onClick={() => { system.decideTimesheet(sheet.id, "Approved", "Allocation and work unit validated"); onToast(`${sheet.id} approved`); }}>Approve week</button></> : <button className="primary-button" disabled={sheet.state !== "Draft" || total === 0} onClick={() => { system.submitTimesheet(sheet.id); onToast(`${sheet.id} submitted for manager review`); }}>Submit week →</button>}</div></div></section></>;
}

export function CommandDemo({ screen, system, onSelect }: { screen: ScreenSpec; system: DemoSystem; onSelect: (id: string) => void }) {
  const approvedRevenue = system.state.budgets.filter((item) => item.state === "Approved").reduce((sum, item) => sum + item.revenue, 0);
  const actualHours = system.state.timesheets.filter((item) => item.state === "Approved").reduce((sum, item) => sum + item.hours.reduce((a, b) => a + b, 0), 0);
  return <><DemoBanner label={`${screen.id} · certified demo cutoff 22 Aug 2026 12:15 IST`} title={screen.title} description="Every KPI exposes its population, cutoff and drill path; values update from the browser transaction ledger." /><section className="stat-grid"><article className="stat-card"><div><span>Approved revenue</span></div><strong>{currency.format(approvedRevenue)}</strong><p>Current approved signatures</p></article><article className="stat-card"><div><span>Accepted allocations</span></div><strong>{system.state.allocations.length}</strong><p>Committed capacity only</p></article><article className="stat-card"><div><span>Approved actuals</span></div><strong>{actualHours}h</strong><p>Submitted time excluded</p></article><article className="stat-card"><div><span>Audit events</span></div><strong>{system.state.audit.length}</strong><p>Current demo ledger</p></article></section><section className="dashboard-grid"><article className="surface chart-panel large-chart"><div className="surface-heading"><div><span className="section-kicker">Effective-dated allocation</span><h2>Capacity by practitioner</h2></div></div><div className="horizontal-bars">{system.state.people.map((person) => { const committed = system.state.allocations.filter((item) => item.employee === person.name).reduce((sum, item) => sum + item.allocation, 0); return <button key={person.id} onClick={() => onSelect("SKLUI-05")}><span>{person.name}</span><i><b style={{ width: `${committed}%` }} /></i><strong>{committed}%</strong></button>; })}</div></article><article className="surface"><div className="surface-heading"><div><span className="section-kicker">Decision quality</span><h2>Control status</h2></div></div><div className="control-status"><p><DemoTag tone="good">Fresh</DemoTag><span>People Master</span><b>12m</b></p><p><DemoTag tone="good">Reconciled</DemoTag><span>Budget service</span><b>Live</b></p><p><DemoTag tone="good">Current</DemoTag><span>Staffing ledger</span><b>Live</b></p><p><DemoTag tone="warn">Pending</DemoTag><span>Timesheet approvals</span><b>{system.state.timesheets.filter((item) => item.state === "Submitted").length}</b></p></div></article></section></>;
}

export function AdminDemo({ screen, system, onToast }: { screen: ScreenSpec; system: DemoSystem; onToast: (message: string) => void }) {
  if (screen.id === "ADMUI-08" || screen.id === "CMD-09") return <><DemoBanner label="Immutable browser demo ledger" title="Audit and operations" description="Every demo decision records actor, active role, entity, timestamp and attributable detail."><button className="secondary-button inverse" onClick={() => onToast("Sanitized audit export prepared in the demo")}>Export sanitized log</button></DemoBanner><section className="surface data-surface"><div className="responsive-table"><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Actor</th><th>Active role</th><th>Detail</th></tr></thead><tbody>{system.state.audit.map((item) => <tr key={item.id}><td>{item.time}</td><td><strong>{item.action}</strong></td><td>{item.entity}</td><td>{item.actor}</td><td>{item.role}</td><td>{item.detail}</td></tr>)}</tbody></table></div></section></>;
  return <><DemoBanner label={`${screen.id} · static demo controls`} title={screen.title} description="Configuration mutations are browser-scoped, sanitized and recorded in the demo ledger." /><section className="admin-grid">{[["Identity and roles", roles.length, "Healthy"], ["Budget policies", 1, "Active"], ["Capability catalogue", 14, "Healthy"], ["Integration façades", 5, "Simulated"], ["Notification templates", 9, "Active"], ["Audit events", system.state.audit.length, "Current"]].map(([label, count, status]) => <button className="admin-card" key={String(label)} onClick={() => onToast(`${label} opened in read-only demo mode`)}><span>⚙</span><div><strong>{label}</strong><small>{count} configured</small></div><DemoTag tone="good">{String(status)}</DemoTag><b>→</b></button>)}</section><section className="surface"><div className="surface-heading"><div><span className="section-kicker">Demo environment controls</span><h2>Safe reset and operating boundary</h2></div></div><div className="admin-notice"><p><strong>No EXL production data or credentials</strong><span>All records are sanitized fixtures stored only in this browser.</span></p><button className="secondary-button danger" onClick={() => { system.reset(); onToast("All browser demo data restored to its signed baseline"); }}>Reset complete demo</button></div></section></>;
}
