trigger Resource360ConfigurationGuard on R360_Configuration__c (before insert,before update,before delete) {
    Boolean authorized=FeatureManagement.checkPermission('Resource360_Manage_Configuration')||FeatureManagement.checkPermission('Resource360_Approve_Configuration');
    if(!authorized){for(R360_Configuration__c record:Trigger.isDelete?Trigger.old:Trigger.new)record.addError('A dedicated Resource360 configuration permission is required.');}
    if(Trigger.isDelete){for(R360_Configuration__c record:Trigger.old)if(record.State__c=='Active'||record.State__c=='Retired'||record.State__c=='Pending Approval')record.addError('Submitted and effective configuration evidence cannot be deleted.');}
    if(Trigger.isInsert){for(R360_Configuration__c record:Trigger.new){if(record.State__c!='Draft')record.addError('New configuration must start as Draft.');for(String error:Resource360ConfigurationService.validateRecord(record))record.addError(error);}}
    if(Trigger.isUpdate){
        Map<String,Set<String>>allowed=new Map<String,Set<String>>{'Draft'=>new Set<String>{'Draft','Pending Approval'},'Rejected'=>new Set<String>{'Draft','Pending Approval'},'Pending Approval'=>new Set<String>{'Active','Rejected'},'Active'=>new Set<String>{'Active','Retired'},'Retired'=>new Set<String>{'Retired'}};
        for(R360_Configuration__c record:Trigger.new){R360_Configuration__c prior=Trigger.oldMap.get(record.Id);if(!allowed.get(prior.State__c).contains(record.State__c))record.addError('Invalid configuration state transition from '+prior.State__c+' to '+record.State__c+'.');if((prior.State__c=='Pending Approval'||prior.State__c=='Active'||prior.State__c=='Retired')&&(record.Configuration_Key__c!=prior.Configuration_Key__c||record.Domain__c!=prior.Domain__c||record.Code__c!=prior.Code__c||record.Display_Label__c!=prior.Display_Label__c||record.Value_Type__c!=prior.Value_Type__c||record.Numeric_Value__c!=prior.Numeric_Value__c||record.Text_Value__c!=prior.Text_Value__c||record.Boolean_Value__c!=prior.Boolean_Value__c||record.Attributes_JSON__c!=prior.Attributes_JSON__c||record.Unit__c!=prior.Unit__c||record.Effective_From__c!=prior.Effective_From__c||record.Version__c!=prior.Version__c||record.Version_Key__c!=prior.Version_Key__c||record.Release_Key__c!=prior.Release_Key__c))record.addError('Submitted or effective configuration identity, release and value are immutable; create a new version.');for(String error:Resource360ConfigurationService.validateRecord(record))record.addError(error);}
    }
}
